### ISSUE TITLE
Switching Networks on Bridge not functioning correctly

### ISSUE THREAD

**Issue by jemeza** [bobanetwork/gateway#112]
## Issue Type

```
[ x] bug report
[ ] feature request
```

## Current Behavior
After working through the flow to switch networks and approving the switch on Metamask the user must once again click the connect button and select a the Metamask wallet in order to get connected to the gateway.

## Expected Behavior
After working through the flow to switch networks and approving the switch on Metamask the user should not have to connect the wallet once again.

## Steps to Reproduce
1. Connect Wallet to gateway
2. Switch to a different network 
3. Approve network change on Metamask

**Comment by sk-enya** [comment]
Already fixed, no more relevant
