### ISSUE TITLE
Replace Goerli with Sepolia.

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/gateway#307]
## Issue Type

```
[ ] bug report
[x] feature request
```

## Current Behavior

Remove goerli and get the sepolia rpc added

sepolia.boba.network

## Steps to Reproduce

1.
2.
3.

## Suggested Fix

Make sure everything works correctly on sepolia network.

**Comment by Boyuan-Chen** [comment]
Can we keep them both live for a month before we take down the goerli?

**Comment by sk-enya** [comment]
Good point! will need to make changes accordingly!

@wsdt please let me know if anything needed from me.

**Comment by wsdt** [comment]
already on it :-) 
thanks! will push it today ideally and then let's go from there
