### ISSUE TITLE
Fix Dao on gateway

### ISSUE THREAD

**Issue by souradeep-das** [bobanetwork/gateway#322]
The DAO on https://gateway.boba.network/dao doesn't load/fetch proposals and seems broken

Expected behaviour: 
-- Proposals are displayed
to ensure:
-- All dao modules work on the gateway including - Voting on proposals works on the gateway, delegating votes and creating proposals.
-- the reason it stopped working
-- subgraphs (identified to be the issue) needs to be deployed to enable Dao 'proposals' query

**Comment by souradeep-das** [comment]
@wsdt for helping with deploying the goldsky subgraphs

**Comment by wsdt** [comment]
Just to avoid any double work: 
- If someone sends me the contract address + ABI. I'll deploy it directly. 
- Just prepared the relevant code part and pushed to the anchorage/bridging branch.

**Comment by wsdt** [comment]
only Boba ETH right?

**Comment by souradeep-das** [comment]
thanks, sent you the address and contract
