### ISSUE TITLE
Sepolia Testnet Bugs

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/gateway#341]
1.  I can’t switch from Goerli to Sepolia. The `Ethereum (Sepolia)` button doesn't work.
![image_720](https://github.com/bobanetwork/gateway/assets/46272347/b03be6a0-797a-4097-b8f0-8cae59b8b01c)
2. (minor) Can we set Sepolia Testnet as the default one when you switch from the mainnet to the testnets?
3. Can we add the BOBA to the token list? https://sepolia.etherscan.io/token/0x33faF65b3DfcC6A1FccaD4531D9ce518F0FDc896
4. The block confirmation is removed for now. Can we remove this when you deposit from L1 to L2? `Current blocks : 0/64`
5. The anchorage endpoint is `https://sepolia.boba.network/`. The network name is Boba Sepolia Testnet rather than Anchorage L2.
6. The withdrawal doesn’t work. The TX is not popped up in the metamask when I clicked `initiate withdrawal`

**Comment by sk-enya** [comment]
Thank you @Boyuan-Chen will take look!

**Comment by sk-enya** [comment]
@boyuan-chen 

>> 2 (minor) Can we set Sepolia Testnet as the default one when you switch from the mainnet to the testnets?
I would request hold on this as it will just make the code bit messy as soon as we removed goerli it will be by default the sepolia testnet on switching from mainnet to testnet.

**Comment by sk-enya** [comment]
@boyuan-chen can you please share any snapshot for issue 5 as I am unable to find it on gateway!

**Comment by sk-enya** [comment]
>> The withdrawal doesn’t work. The TX is not popped up in the metamask when I clicked initiate withdrawal

Looks like working for me please test again with new release!
