### ISSUE TITLE
Sepolia L2 issue

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/gateway#348]
1. If you cancel the transaction, it skips the current step and goes the next one.
2. If I close the modal in the middle of the process, where can I find it back?
3. The history section doesn't work.

**Comment by sk-enya** [comment]
@wsdt can you please give more details on points 2/ & 3/? 
How are we going to handle the pending txs on history?

**Comment by wsdt** [comment]
2. If I close the modal in the middle of the process, where can I find it back?

The gateway picks up where you left of in the background and shows a notification for the user to proceed. Furthermore, the user can continue on the history page, there is a button if there are actions pending. 


3. What doesn't work? @sk-enya could this be related to the new sepolia/goerli upgrade?

**Comment by boyuan-chen** [comment]
The exit amount and token is not correct.
![image](https://github.com/bobanetwork/gateway/assets/46272347/0cc5d812-a3f7-4db2-ac2d-0ccd86cba7fc)

**Comment by boyuan-chen** [comment]
Can we reduce the loading time for the history page? Something goes wrong. The exit transaction popped up after I picked the `From` and `To` networks.

**Comment by boyuan-chen** [comment]
The metamask doesn't pop up when I try to prove the withdrawal.
![image](https://github.com/bobanetwork/gateway/assets/46272347/f6a1880e-a216-41f8-92ed-aa752b5c9228)

**Comment by sk-enya** [comment]
@boyuan-chen all the issues fixes except the `Can we reduce the loading time for the history page? Something goes wrong. The exit transaction popped up after I picked the From and To networks.` we will consider in the another [issue](https://github.com/bobanetwork/gateway/issues/314)

**Comment by sk-enya** [comment]
Closing as all the changes has been done with 
https://github.com/bobanetwork/gateway/pull/350

**Comment by boyuan-chen** [comment]
@sk-enya @wsdt  new issues:
1. I have submitted the proof first. However, I can't claim the withdrawal. The metamask didn't pop up.
2. When I reopen the modal, it goes back to the `submit proof` step.
<img width="465" alt="image" src="https://github.com/bobanetwork/gateway/assets/46272347/c8bcbe29-9536-4596-bd23-75773fa03891">

**Comment by sk-enya** [comment]
@wsdt  looks like when user comes back to the modal above after proving withdrawal the claim button won't work as value of latestLogs always null if we directly open the modal in proven state.

https://github.com/bobanetwork/gateway/blob/1384eeb6c3ce2f968e222761e0548f8cf860e0c0/src/containers/modals/MultiStepWithdrawalModal/VerticalStepper.tsx#L99

**Comment by sk-enya** [comment]
Can you please look into? here is the updated PR  with other broken changes for bridging & history page.

**Comment by wsdt** [comment]
does your PR fix the issue above? @sk-enya

**Comment by sk-enya** [comment]
@wsdt updated pull request with changes done as points

**Comment by sk-enya** [comment]
@wsdt the question is about the claim features when you open the already proven transactions which is not getting triggered!

it's seems already in anchorage change nothing has change because of goerli sepolia supports!

**Comment by sk-enya** [comment]
> @sk-enya @wsdt new issues:
> 
> 1. I have submitted the proof first. However, I can't claim the withdrawal. The metamask didn't pop up.
> 2. When I reopen the modal, it goes back to the `submit proof` step.
> 
> <img alt="image" width="465" src="https://private-user-images.githubusercontent.com/46272347/307178832-c8bcbe29-9536-4596-bd23-75773fa03891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjM2MjIsIm5iZiI6MTcwOTcyMzMyMiwicGF0aCI6Ii80NjI3MjM0Ny8zMDcxNzg4MzItYzhiY2JlMjktOTUzNi00NTk2LWJkMjMtNzU3NzNmYTAzODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDExMDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOTYxYTgzMGIxYTQ2YWU5MzcwZThkMjI3MTc5NGQzMjljMDY0YjlmYWMzYzNiOTBlYmYyOTQ4MTI3ZDMyNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XKQO5cKTdNPP_K6Z3O31qxyyPHsET5FMWA5I2VXELvI">

Added fix for this in PR https://github.com/bobanetwork/gateway/pull/378

**Comment by sk-enya** [comment]
Changes has been taken care so closing the issue, please feel free to create new or open open the issue again!
