### ISSUE TITLE
[Gateway] Make Gateway support OVM and Bedrock rollup

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/gateway#37]
## Issue Type

```
[ ] bug report
[x ] feature request
```

## Current Behavior
Currently the gateweay lives in this repository within packages/boba/gateway. Going forward, gateway should live in 
https://github.com/bobanetwork/gateway - a new public repository.

## Expected Behavior
The gateway communicates with the blockhain using RPC to a blockchain node - this blockchain node can be either the existing one https://github.com/bobanetwork/boba or the one in https://github.com/bobanetwork/v3-anchorage.

## Steps to Reproduce

1.
2.
3.

**Comment by sk-enya** [comment]
Closing as this is pretty much handled and supported on sepolia network!
