### ISSUE TITLE
Bridge: Token picker

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/gateway#42]

**Comment by jemeza** [comment]
@sk-enya, when bridging tokens from L1 to L2 and L2 to L1 the token picker is utilized. Is this sufficient or would you like to see other tests?

**Comment by sk-enya** [comment]
I would expect to see the token picker with this flow.

1. Should open token picker
2. should show the loading 
3. should show the listing tokens
4. Should select the token and check state update in redux.
5. close modal
6. check add token to metamask is also functional.


If it's already covered then we are good to skip and mark this as completed.

**Comment by jemeza** [comment]
In the current implementation there isn't a loading Icon that appears, should I make this a separate issue?

**Comment by sk-enya** [comment]
> @sk-enya, In the current implementation there isn't a loading Icon that appears, should I make this a separate issue?

@jemeza  yes please!
