### ISSUE TITLE
Disable Bridge Option which is not a supported Route!

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/gateway#453]
## Issue Type

```
[x] bug report
[ ] feature request
```

Whenever a user is bridging from Boba ETH to a different chain, only the ones available pop up?

**Comment by sk-enya** [comment]
@wsdt is there any way to identify supported target route for selected network ?

**Comment by wsdt** [comment]
Are you talking about lightbridge or anchorage bridging? 

LightBridge already only shows supported tokens in the token picker.

**Comment by sk-enya** [comment]
@wsdt it's about the light bridge. supported token is good, Gian propose to disable the target chain if it's not valid route. 

like from : BNB then to: should only show supported doesn't make sense to have goerli & ethereum if no round available!
