### ISSUE TITLE
Button duplicate or wrong labelling

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/gateway#52]
## Issue Type

```
[x ] bug report
[ ] feature request
```

## Current Behavior
"Pools" button on the "Earn" page is duplicate or has the wrong label. 
![image](https://github.com/bobanetwork/gateway/assets/28724551/7310d960-b7a3-4d43-bb5e-bedcda0f6656)

## Steps to Reproduce
Live on production: https://gateway.boba.network/earn

## Suggested Fix
Either remove one button or change the label to the right one.

**Comment by sk-enya** [comment]
It would be great if you can add steps to reproduce please!

**Comment by wsdt** [comment]
Actually just opened the page and had that issue. 

Maybe it was just a flake - can't re-produce it anymore now as well.
