### ISSUE TITLE
Deprecating "Earn"

### ISSUE THREAD

**Issue by thenursegreg42069** [bobanetwork/gateway#59]
With the upcoming launch of the Boba Light Bridge (formerly Teleportation), the Earn program is now superfluous. The Earn program should be deprecated.

NB: Light Bridge is currently on testnet and needs a few weeks of testing before a mainnet release.

- [x] 1. Place a message on the current Earn page: "To prepare for the upcoming release of the Boba Light Bridge, the Earn program is being sunsetted. Deposits will be turned off on [X date] and an interface will be available indefinitely to withdraw user funds.
- [x] 2. Turn off Earn deposits (to be coordinated with the mainnet launch of Light Bridge)
- [x] 3. Remove the Earn link from the gateway header
- [ ] 4. Develop a withdraw only Earn UI. This should be supported indefinitely, or until there are zero user funds remaining.
- [x] 5. Place a link to 4 somewhere on the Gateway (defer to yoonhee on best placement)

**Comment by sk-enya** [comment]
- [x] Place a message on the current Earn page: "To prepare for the upcoming release of the Boba Light Bridge, the Earn program is being sunsetted. Deposits will be turned off on [X date] and an interface will be available indefinitely to withdraw user funds.
- [x] Turn off Earn deposits / stake with tooltip why it's disabled (to be coordinated with the mainnet launch of Light Bridge)
- [x] Remove the Earn link from the gateway header
- [x] Place a link to 4 somewhere on the Gateway (defer to yoonhee on best placement) : banner added with links.

**Comment by sk-enya** [comment]
Now we only have to update the unstake UI.

- [ ] Develop a withdraw only Earn UI. This should be supported indefinitely, or until there are zero user funds remaining.
