### ISSUE TITLE
3rd Party Bridges In separate Tab: 

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/gateway#63]
![Image](https://user-images.githubusercontent.com/81116391/234365132-bfc3db5a-4773-448a-9e32-64f370b7911f.svg)

I have created a simple design to implement Banxa in our bridge. Although the content of the current design is different from what we have in version 2 of our gateway, since they are tabs, we can implement the same functionality directly in our current bridge without having to wait for version 2.5.

I also added examples for when we implement other bridges like Simplex in the future, to have an idea of how the functionality and component would look visually.

https://www.figma.com/file/zWdKbazMwugNWLjqukOMIU/Untitled?node-id=0-1&t=ozoiLylkDpGAe4V5-0

**Comment by yhong1073** [comment]
Redesigned the three tab design and third party bridges in Figma! 
https://www.figma.com/file/MKj9nofAYq0GOTziHaeWRL/Boba-Gateway-2.5?type=design&node-id=108%3A1884&mode=design&t=QuVYEZvLEkH6uAjV-1
The redesigned third party bridges section is located by a figma comment mentioning "third party."

**Comment by sk-enya** [comment]
Hello, @thenursegreg42069 @InoMurko 

Currently, we are showing 3rd party bridges only on **Mainnet** for a selected token that users want's to bridge, so just need your defined the user flow for below scenarios where we don't have 3rd party bridges. 
1. when user not connected
2. when user connected to TESTNET


Do we have to keep the 3rd party bridges tab enable with blank `No 3rd party bridge available`

**Comment by sk-enya** [comment]
@yhong1073 can you please help me with creating Icons for all the available bridges listed in the image attached along with below scenarios.

1/ dark & light mode
2/ we have to put some max height so what will be that?
3/ in case of BNB we don't have any bridges so share some thoughts No bridges available on screen!

![Screenshot 2023-11-03 at 7 22 24 PM](https://github.com/bobanetwork/gateway/assets/86316370/0dbeef24-f409-4032-807c-3823d839e0bb)

**Comment by yhong1073** [comment]
Here are the third party icons. Only two logos needed to have separate light and dark mode icons. Icons are enlarged for quality sake.
[Third Party icons.zip](https://github.com/bobanetwork/gateway/files/13253160/Third.Party.icons.zip)

**Comment by yhong1073** [comment]
https://www.figma.com/file/MKj9nofAYq0GOTziHaeWRL/Boba-Gateway-2.5?type=design&node-id=3119%3A1656&mode=design&t=fOcEMUQ0kkaKjyHy-1
Specifics about the third party bridges tab are updated. Locate it through recent figma comment mentioning third party bridges.
