### ISSUE TITLE
Integrate new Testnet/Mainnet Captcha Faucet in Gateway

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/gateway#68]
## Issue Type

```
[ ] bug report
[ x] feature request
```

## Current Behavior
Gateway uses workaround faucet (no captcha) as the Twitter check had been removed since Twitter API is now paid. 

## Expected Behavior
integrate new simple hcaptcha faucet into Gateway: 
https://github.com/bobanetwork/boba/issues/996

e.g. remove Twitter input, etc. but add HCaptcha check

Just added you @sk-enya , please obviously feel free to assign to whoever you think is right etc.

**Comment by sk-enya** [comment]
As discussed with @wsdt we are going to prepare separate website for faucet  from 
https://github.com/bobanetwork/Faucet/tree/master

**Comment by wsdt** [comment]
> As discussed with @wsdt we are going to prepare separate website for faucet from https://github.com/bobanetwork/Faucet/tree/master

The one above most likely, so no :-)
