### ISSUE TITLE
Gateway : Emergency Swap

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/gateway#70]
### 2.6

**Comment by wsdt** [comment]
Guess this is then also redundant and done? @sk-enya 
or are we planning on removing the emergency swap altogether?

**Comment by sk-enya** [comment]
@wsdt @souradeep-das do we really need emergency swap now?

Shall I get it clean up?

**Comment by sk-enya** [comment]
As per the comment from @boyuan-chen  changes done in PR https://github.com/bobanetwork/gateway/pull/455
```
The dual fee token will be removed on Ethereum L2s. We can remove it on Sepolia L2 and Eth L2, but please keep them on Bnb testnet L2 and Bnb L2.
```

**Comment by wsdt** [comment]
Once we have the mainnet/testnet faucets & now with the lightbridge (that also includes an airdrop feature) I think we should be fine with removing it? @souradeep-das

**Comment by sk-enya** [comment]
@wsdt as per the comment from @boyuan-chen we are still supporting it for BNB so already handled changes under #455
