### ISSUE TITLE
Gateway: Use `JsonRpcBatchProvider` for some RPC calls

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/gateway#72]
## Issue Type

```
[ ] bug report
[x] feature request
```

## Steps to Reproduce

1.
2.
3.

## Suggested Fix

https://docs.ethers.org/v5/api/providers/other/#JsonRpcBatchProvider

We can batch our requests and send to the node.
Note:
The maximum batch size of our RPC is 5.

**Comment by sk-enya** [comment]
@boyuan-chen Is this still valid? can you please help me with an use case of using this?
