### ISSUE TITLE
When bridging from L1 to Alt-L1, Regardless if you approved the boba spending limit, if you cancel the bridge, you will need to approve it again.

### ISSUE THREAD

**Issue by GianBobarino** [bobanetwork/gateway#74]
![Image](https://user-images.githubusercontent.com/123008441/232597558-53349477-cfe1-4d99-9061-940633e2ad39.png)

I had to approve twice for the same transaction. 

What happened: I had enough ETH on the UI while bridging, however, once I had to accept boba spending limit, that ate into my eth therefore not having enough to actually bridge. When I cancelled the transaction to bridge more eth, once initiating bridge again, I had to approve spending limit again.

What it should be: Approve Spending limit once even if you cancel bridge.

**Comment by sk-enya** [comment]
No longer valid.
