### ISSUE TITLE
Support Teleportation in gateway

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/gateway#78]
The teleportation button should be added to the `wallet` page. Besides that, it can be added to the bridge page that users can pick two L2s.

![Image](https://user-images.githubusercontent.com/46272347/222220993-546d823d-be3e-45e5-a4fc-748467e71913.png)

**Comment by wsdt** [comment]
@sk-enya is this still relevant?
I guess with Yoonhee's mockups etc. this is redundant?

**Comment by sk-enya** [comment]
Yeah we can close this it's not relevant anymore.
