### ISSUE TITLE
[Gateway] : Add multi lingul support.

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/gateway#81]
## Issue Type

[ ] bug report
[x] feature request

## Current Behavior

Currently gateway doesn't support multi-lingual so good to have that as feature.

```
NOTE: from kevin.
Have we actually ever thought about translating?
Having a i18n json file giving it to some freelancer on Fiverr for a small fee and having a multi-lingual site etc. (only a small fraction of the world population speaks English)
```

## Expected Behavior

We should support the multi lingual on gateway.

## Steps to Reproduce

1.
2.
3.

## Suggested Fix

Lingui will have better support with react and good for translation and prepare multi-lingul site.

https://lingui.js.org/
React package we can make use of `@lingui/react`

**Comment by InoMurko** [comment]
Isn’t needed and no one will be able to maintain this.
