### ISSUE TITLE
[gateway] integrate Banxa fiat-on ramp

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/gateway#82]
## Issue Type

```
[ ] bug report
[x ] feature request
```

## Current Behavior
There's no FIAT on ramp

## Expected Behavior
Integrate https://docs.banxa.com/docs
on Ethereum BOBA ONLY.

## Steps to Reproduce

1. https://arbitrum.banxa.com/
2. 
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/2582555/199533940-d5d66bfc-5d86-46b0-af65-21f213f55544.png">

3.

**Comment by sk-enya** [comment]
@alvaro-ricotta @souradeep-das is there anything need to be done or is this issue still valid ?

**Comment by souradeep-das** [comment]
closing this as done through https://github.com/bobanetwork/boba/commit/33ace72ccdc8eeadbe98b9a08af30cc25692afc5
