### ISSUE TITLE
Gateway - Shut down fast bridges and point to across.to

### ISSUE THREAD

**Issue by berabuilder** [bobanetwork/gateway#84]
- Announce shut down of fast bridge so users can withdraw (rebalance if necessary)
- Disable deposits
- Remove fast bridge from frontend once most users withdrew
- Provide guide to withdraw liquidity via blockexplorer once frontend is down (for late comers)

**Comment by wsdt** [comment]
Guess this issue is not relevant anymore right? 
At least the Across part. 

Created a new issue on the gateway (for at least the frontend tasks): 
https://github.com/bobanetwork/gateway/issues/87

**Comment by sk-enya** [comment]
Awesome, closing this issue now as not relevant!
