### ISSUE TITLE
Deprecate Fast bridge in favor of Light bridge

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/gateway#87]
Related to https://github.com/bobanetwork/gateway/issues/58

Fast bridge is being deprecated in favor of light bridge. 

On the Gateway/UI front we may want to remove the tab for "FAST" bridging and related code on the history page etc. once light bridge is live on mainnet. 

## Issue Type

```
[ ] bug report
[ x] feature request
```

## Current Behavior
Fast bridge will be deprecated in favor of light bridge: 
https://github.com/bobanetwork/gateway/issues/58

## Expected Behavior
Remove Fast bridge from bridge tabs and possibly redundant code (e.g. history etc.).
![image](https://github.com/bobanetwork/gateway/assets/28724551/19d19065-bf4e-4db0-9476-3a73153e9f54)

**Comment by sk-enya** [comment]
Closing as it's already taken care and ship to production!
