### ISSUE TITLE
Gateway: Banner to sunset Earn Page

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/gateway#88]
## Issue Type

```
[x] bug report
[ ] feature request
```

## Expected Behavior

![Screenshot 2023-10-09 at 9 57 54 AM](https://github.com/bobanetwork/gateway/assets/86316370/175cdf0d-8c5d-45f7-ab09-39a40cc11acd)

@thenursegreg42069 @yhong1073 
1. Click here will navigate the user to Earn page right?
2. This has to go with light bridge or needed earlier to that on productions ?

**Comment by yhong1073** [comment]
1. Yes, but a modified Earn page for users to withdraw funds. It should be labeled Light/dark_Earn_Withdraw in the figma file. 
https://www.figma.com/file/MKj9nofAYq0GOTziHaeWRL/Boba-Gateway-2.5?type=design&node-id=108%3A1884&mode=design&t=n8nBmaFG2MnOTIDx-1

**Comment by thenursegreg42069** [comment]
1. Yes per Yoonhee above.
2. It should not go live until the light bridge is ready - if users start removing funds, the current fast bridge will not function as well, without Light Bridge available to replace it.

**Comment by sk-enya** [comment]
Awesome, thanks!
