### ISSUE TITLE
bottom bar that shows network details isn't working

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/gateway#96]
## Issue Type

```
[x ] bug report
[ ] feature request
```

## Current Behavior
<img width="1470" alt="image" src="https://github.com/bobanetwork/gateway/assets/2582555/c069e46b-48e4-471a-9172-6540421d7be5">

<img width="882" alt="image" src="https://github.com/bobanetwork/gateway/assets/2582555/a29c5ec4-5adc-40ba-b5d4-373aed0c6903">

## Expected Behavior
It seems like these three items are not workign correctly! (on any network!)
Boba ETH
0 Gwei
Savings
0x
Last Verified Block
935931

Last Verified Block is stale, saving and gas fee is not calculated.
## Steps to Reproduce

1.
2.
3.

**Comment by thenursegreg42069** [comment]
@alvaro-ricotta @sk-enya can you take a look at this and make sure the data is being displayed correctly? It appears from my end to still not be correct.

**Comment by sk-enya** [comment]
Sure, will take look!
